### ISSUE TITLE
Entorno de pruebas y nuevo site 2020

### ISSUE THREAD

**Issue by eduherraiz** [python-spain/web-pycones#19]
Es necesario tener desplegado un entorno nuevo (test) para probar cambios de arquitectura de aplicación antes de pasar a las webs productivas.
También estaría muy bien dar salida a la nueva web de pycones 2020 aunque sea privada para los organizadores.

Por eso pongo este issue aquí para, si os parece bien, crear estos dos entornos en infraestructura actual.

Será necesario retocar CI para tener todo esto en cuenta.

**Comment by aaloy** [comment]
thanks!
